function [DT,Dx,Dy,Dz,Jx,Jy,Jz,ET,Ex,Ey,Ez,Bx,By,Bz,Hx,Hy,Hz,CDxy,CDyx,CDyz,CDzy,CDzx,CDxz,CHxy,CHyx,CHyz,CHzy,CHzx,CHxz,...
    bx,by,bz,axd,ayd,azd,kdx,kdy,kdz,G_Distrtn] = intialize_E_H_Fields_CPML_sep(Nx,Ny,Nz,CPML)
    [DT] = deal(zeros(Nx+1,Ny+1,Nz+1)); % DT cells
    [ET] = deal(zeros(Nx+1,Ny+1,Nz+1)); % ET cells
    [Dx] = deal(zeros(Nx,Ny+1,Nz+1)); % Dx cells
    [Dy] = deal(zeros(Nx+1,Ny,Nz+1)); % Dy cells
    [Dz] = deal(zeros(Nx+1,Ny+1,Nz)); % Dz cells
    [Ex] = deal(zeros(Nx,Ny+1,Nz+1)); % Ex cells
    [Ey] = deal(zeros(Nx+1,Ny,Nz+1)); % Ey cells
    [Ez] = deal(zeros(Nx+1,Ny+1,Nz)); % Ez cells
    [Jx] = deal(zeros(Nx,Ny+1,Nz+1)); % Jx cells
    [Jy] = deal(zeros(Nx+1,Ny,Nz+1)); % Jy cells
    [Jz] = deal(zeros(Nx+1,Ny+1,Nz)); % Jz cells
    [Bx] = deal(zeros(Nx+1,Ny,Nz)); % Bx cells
    [By] = deal(zeros(Nx,Ny+1,Nz)); % By cells
    [Bz] = deal(zeros(Nx,Ny,Nz+1)); % Bz cells
    [Hx] = deal(zeros(Nx+1,Ny,Nz)); % Hx cells
    [Hy] = deal(zeros(Nx,Ny+1,Nz)); % Hy cells
    [Hz] = deal(zeros(Nx,Ny,Nz+1)); % Hz cells
    [CDyx] = deal(zeros(Nx+1,2*CPML,Nz)); % CDyx cells
    %[CDyx] = deal(zeros(Nx+1,Ny,Nz)); % CDyx cells
    [CDxy] = deal(zeros(2*CPML,Ny+1,Nz)); % CDxy cells
    %[CDxy] = deal(zeros(Nx,Ny+1,Nz)); % CDxy cells
    [CDxz] = deal(zeros(2*CPML,Ny,Nz+1)); % CDxz cells
    %[CDxz] = deal(zeros(Nx,Ny,Nz+1)); % CDxz cells
    [CDzx] = deal(zeros(Nx+1,Ny,2*CPML)); % CDzx cells
    %[CDzx] = deal(zeros(Nx+1,Ny,Nz)); % CDzx cells
    [CDzy] = deal(zeros(Nx,Ny+1,2*CPML)); % CDzy cells
    %[CDzy] = deal(zeros(Nx,Ny+1,Nz)); % CDzy cells
    [CDyz] = deal(zeros(Nx,2*CPML,Nz+1)); % CDyz cells
    %[CDyz] = deal(zeros(Nx,Ny,Nz+1)); % CDyz cells
    [CHyx] = deal(zeros(Nx,2*CPML,Nz+1)); % CHyx cells
    %[CHyx] = deal(zeros(Nx,Ny,Nz+1)); % Ex cells
    [CHxy] = deal(zeros(2*CPML,Ny,Nz+1)); % CHxy cells
    %[CHxy] = deal(zeros(Nx,Ny,Nz+1)); % Ey cells
    [CHxz] = deal(zeros(2*CPML,Ny+1,Nz)); % CHxz cells
    %[CHxz] = deal(zeros(Nx,Ny+1,Nz)); % Ez cells
    [CHzx] = deal(zeros(Nx,Ny+1,2*CPML)); % CHzx cells
    %[CHzx] = deal(zeros(Nx,Ny+1,Nz)); % Ex cells
    [CHzy] = deal(zeros(Nx+1,Ny,2*CPML)); % CHzy cells
    %[CHzy] = deal(zeros(Nx+1,Ny,Nz)); % Ey cells
    [CHyz] = deal(zeros(Nx+1,2*CPML,Nz)); % CHyz cells
    %[CHyz] = deal(zeros(Nx+1,Ny,Nz)); % Ez cells
%{
    [CHyz] = deal(zeros(Nx+1,2*CPML,Nz)); % CHyz cells
    [CHzy] = deal(zeros(Nx+1,Ny,2*CPML)); % CHzy cells
    [CHzx] = deal(zeros(Nx,Ny+1,2*CPML)); % CHzx cells
    [CHxz] = deal(zeros(2*CPML,Ny+1,Nz)); % CHxz cells
    [CHxy] = deal(zeros(2*CPML,Ny,Nz+1)); % CHxy cells
    [CHyx] = deal(zeros(Nx,2*CPML,Nz+1)); % CHyx cells
    [CDyz] = deal(zeros(Nx,2*CPML,Nz+1)); % CDyz cells
    [CDzy] = deal(zeros(Nx,Ny+1,2*CPML)); % CDzy cells
    [CDzx] = deal(zeros(Nx+1,Ny,2*CPML)); % CDzx cells
    [CDxz] = deal(zeros(2*CPML,Ny,Nz+1)); % CDxz cells
    [CDxy] = deal(zeros(2*CPML,Ny+1,Nz)); % CDxy cells
    [CDyx] = deal(zeros(Nx+1,2*CPML,Nz)); % CDyx cells
%}
    [bx] = deal(zeros(2*CPML,1));
    [axd] = deal(zeros(2*CPML,1));
    [by] = deal(zeros(1,2*CPML));
    [ayd] = deal(zeros(1,2*CPML));
    [bz] = deal(zeros(1,1,2*CPML));
    [azd] = deal(zeros(1,1,2*CPML));
    [kdx] = deal(zeros(Nx+1,1));
    [kdy] = deal(zeros(1,Ny+1));
    [kdz] = deal(zeros(1,1,Nz+1));
    [G_Distrtn] = deal(zeros(Nx+1,Ny+1));
end